In [1]:
# importing libraries
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [5]:
#importing dataset
df=pd.read_csv('housing.csv')

In [6]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [7]:
# Version of Pandas
pd.__version__

'1.5.3'

In [21]:
# Number of columns in the dataset
df.shape[1]

10

In [12]:
# Select columns with missing data
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [22]:
# Number of unique values in the 'ocean_proximity' column
df['ocean_proximity'].nunique()

5

In [23]:
# Average value of the 'median_house_value' for the houses near the bay
df[df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [24]:
# Calculate the average of total_bedrooms column in the dataset.
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
# Now, calculate the average of total_bedrooms again.
# Has it changed?

df['total_bedrooms'].mean()

537.8705525375618

In [28]:
df['total_bedrooms'].fillna(259212.31179039303).mean()

3132.134570766054

In [58]:
# Select all the options located on islands.
# Select only columns housing_median_age, total_rooms, total_bedrooms.
# Get the underlying NumPy array. Let's call it X.

df_i=df[df['ocean_proximity']=='ISLAND'][['housing_median_age','total_rooms','total_bedrooms']]
X=np.array(df_i)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [54]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX=np.dot(X.T,X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [56]:
# Compute the inverse of XTX.
XTX_I=np.linalg.inv(XTX)
XTX_I

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [57]:
# Create an array y with values [950, 1300, 800, 1000, 1300].
y=np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [70]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the last element of w
w=np.dot(np.dot(XTX_I,X.T),y)
w

array([23.12330961, -1.48124183,  5.69922946])